### ISSUE TITLE
diesel_demo doesn't compile with 0.80 + Sqlite 

### ISSUE THREAD

**Issue by ambaxter** [diesel-rs/diesel#484]
When trying to follow the diesel_demo instructions with sqlite, I get the following error. Any ideas?

```
error[E0277]: the trait bound `i32: diesel::types::FromSqlRow<diesel::types::Nullable<diesel::types::Integer>, _>` is not satisfied
  --> src/bin/show_posts.rs:14:10
   |
14 |         .load::<Post>(&connection)
   |          ^^^^ trait `i32: diesel::types::FromSqlRow<diesel::types::Nullable<diesel::types::Integer>, _>` not satisfied
   |
   = help: the following implementations were found:
   = help:   <i32 as diesel::types::FromSqlRow<diesel::types::Integer, DB>>
   = note: required because of the requirements on the impl of `diesel::types::FromSqlRow<(diesel::types::Nullable<diesel::types::Integer>, diesel::types::Text, diesel::types::Text, diesel::types::Bool), _>` for `(i32, std::string::String, std::string::String, bool)`
   = note: required because of the requirements on the impl of `diesel::Queryable<(diesel::types::Nullable<diesel::types::Integer>, diesel::types::Text, diesel::types::Text, diesel::types::Bool), _>` for `diesel_demo::models::Post`
```

**Comment by sgrif** [comment]
The examples assume the use of PostgreSQL. However that error looks like the schema is incorrect, where a field that should be `NOT NULL` is nullable.
