### ISSUE TITLE
Cannot compile on current Rust nightly (1.42.0)

### ISSUE THREAD

**Issue by dimitarvp** [diesel-rs/diesel#2273]
**HUGE DISCLAIMER:** This issue is about diesel failing to compile on current nightly (1.42.0).

_I am aware the bug template says "your issue will be closed if it cannot be reproduced on the stable channel" but I wanted to make sure the authors are aware of a potential future stable channel compilation failure._

### Versions

- **Rust:** stable (`1.4.0`) and nightly (`1.4.2`)
- **Diesel:** `1.4.3`
- **Database:** PostgreSQL 11.6
- **Operating System:** macOS 10.15.2 Catalina

### Feature Flags

- **diesel:** `features = ["postgres"]`

## Problem Description
I am trying to make a very basic Rocket + Diesel app that simply selects several records from a pre-populated table. While trying with `cargo +stable build` I get errors that Rocket cannot be compiled because it requires nightly:

```plain
Error: Rocket (core) requires a 'dev' or 'nightly' version of rustc.
Installed version: 1.40.0 (2019-12-16)
Minimum required:  1.35.0-nightly (2019-04-05)
...
Error: Rocket (codegen) requires a 'dev' or 'nightly' version of rustc.
Installed version: 1.40.0 (2019-12-16)
Minimum required:  1.33.0-nightly (2019-01-13)
```

Okay, fair enough. Trying with `cargo +nightly build` I get this:

```plain
   Compiling diesel v1.4.3
error[E0275]: overflow evaluating the requirement `<Self as query_dsl::limit_dsl::LimitDsl>::Output`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0275`.
error: could not compile `diesel`.
```

### What are you trying to accomplish?

Compile a hello-world project.

### What is the expected output?

Successful compilation.

### What is the actual output?

Unable to compile on nightly Rust since another project dependency requires it.

### Are you seeing any additional errors?

When passing `--verbose` to the build command, I can see the full command issued:

```plain
     Running `rustc --crate-name diesel /Users/dimi/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 --cfg 'feature="32-column-tables"' --cfg 'feature="bitflags"' --cfg 'feature="default"' --cfg 'feature="postgres"' --cfg 'feature="pq-sys"' --cfg 'feature="with-deprecated"' -C metadata=51aab293bddd2df9 -C extra-filename=-51aab293bddd2df9 --out-dir /Users/dimi/code/rust/hello-rocket/target/debug/deps -L dependency=/Users/dimi/code/rust/hello-rocket/target/debug/deps --extern bitflags=/Users/dimi/code/rust/hello-rocket/target/debug/deps/libbitflags-5150a17c3fe52cc2.rmeta --extern byteorder=/Users/dimi/code/rust/hello-rocket/target/debug/deps/libbyteorder-0b617d0cd30390ec.rmeta --extern diesel_derives=/Users/dimi/code/rust/hello-rocket/target/debug/deps/libdiesel_derives-1c392bec771d33a2.dylib --extern pq_sys=/Users/dimi/code/rust/hello-rocket/target/debug/deps/libpq_sys-c003f05183bc7462.rmeta --cap-lints allow -L 'native=/usr/local/opt/postgresql@11/lib'`
```

### Steps to reproduce

```bash
cargo new hello-world
cd hello-world
```

Put this in the dependencies section of `Cargo.toml`:
```toml
diesel = { version = "1.4.3", features = ["postgres"] }
rocket = "0.4.2"
```

Replace `src/main.rs` with exactly this:

```rust
#![feature(proc_macro_hygiene, decl_macro)]

#[macro_use] extern crate rocket;

#[get("/")]
fn index() -> &'static str {
    "Hello, world!"
}

fn main() {
    rocket::ignite().mount("/", routes![index]).launch();
}
```

(Note diesel isn't even used yet, this is a template Rocket hello-world project.)

Also make sure to have Rust `1.40.0` and `1.42.0` (currently `rustup` views them as `stable` and `nightly`).

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues. (I haven't found a match in the issue tracker using 2 or 3 keywords from the short compiler error output.)
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case). **NOTE:** Only a part of this issue. Diesel compiles just fine on the stable channel. Close the issue if that's your policy, I am simply trying to give an early warning.

**Comment by weiznich** [comment]
Yes we are aware of this issue because that's literally a duplicate of #2247 
Also that's no diesel bug, but a rustc bug and should be reported there (It's already reported as https://github.com/rust-lang/rust/issues/68264)

**Comment by dimitarvp** [comment]
I only searched in the open issues. Apologies and thanks for the links.
