### ISSUE TITLE
Error deriving Insertable for a SQLite table with a nullable timestamp column

### ISSUE THREAD

**Issue by nmusatti** [diesel-rs/diesel#1242]
### Versions

- **Rust:** 1.20.0 (stable)
- **Diesel:** 0.16.0
- **Database:** SQLite 3.7.17
- **Operating System** CentOS 7.4

### Feature Flags

- **diesel:** sqlite chrono
- **diesel_codegen:** sqlite

### What are you trying to accomplish?

I have a table defined as follows:

```sql
create table books (
    id integer not null primary key,
    title varchar null,
    save_date timestamp null 
)
```
I'm trying to derive an `Insertable` implementation for it following roughly the *Getting Started* guide, using `infer_schema!` and the following struct:

```rust
	#[derive(Insertable)]
	#[table_name="books"]
	pub struct NewBook<'a> {
	    pub title : Option<&'a str>,
	    pub save_date : Option<&'a chrono::NaiveDateTime>, 
	}
```

### What is the expected output?

A successful compilation, as is the case with diesel 0.14

### What is the actual output?

A series of error messages complaining for unsatisfied trait bounds, such as these:

    error[E0277]: the trait bound `chrono::NaiveDateTime: diesel::Expression` is not satisfied
      --> src/main.rs:30:11
       |
    30 |    #[derive(Insertable)]
       |             ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `chrono::NaiveDateTime`
       |
       = note: required because of the requirements on the impl of `diesel::Expression` for `&'a chrono::NaiveDateTime`
       = note: this error originates in a macro outside of the current crate
    
    error[E0277]: the trait bound `&'insert domain::NewBook<'a>: diesel::Insertable<schema::__diesel_infer_schema::infer_books::books::table, DB>` is not satisfied
      --> src/main.rs:30:11
       |
    30 |    #[derive(Insertable)]
       |             ^^^^^^^^^^ the trait `diesel::Insertable<schema::__diesel_infer_schema::infer_books::books::table, DB>` is not implemented for `&'insert domain::NewBook<'a>`
       |
       = help: the following implementations were found:
                 <&'insert domain::NewBook<'a> as diesel::Insertable<schema::__diesel_infer_schema::infer_books::books::table, DB>>
       = note: required by `diesel::Insertable`
       = note: this error originates in a macro outside of the current crate

### Are you seeing any additional errors?

The full list of errors can be found in [this gist](https://gist.github.com/nmusatti/89d541ec7582ed32a36ab2185fd7b483).

### Steps to reproduce

[This project](https://github.com/nmusatti/diesel_timestamp_error) exemplifies the problem; uncomment the sections that are commented out and build. If you change the `diesel` and `diesel_codegen` version to 0.14 and `dotenv`'s to 0.9 you'll see that it compiles and runs without problems.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

**Comment by sgrif** [comment]
This appears to have been caused by 38038f6b. It occurs for all reference types except `str` and slices. It's happening because after that commit we are attempting to use a value of type `&'a &'b Value`, which does not implement `AsExpression`.

We haven't implemented that in the past, as there's really no reason to take a reference other than for `str` and slice, since virtually every other type we support is `Copy`. That said, we should probably just allow double references here in general. I really wish we could do a blanket impl for this

**Comment by sgrif** [comment]
I've opened a PR to fix this on master, but I won't be backporting it to 0.16 as there's very little reason to use `&NaiveDateTime` here instead of just `NaiveDateTime`.
