### ISSUE TITLE
Error the trait bound `IpNetwork: diesel::Expression` is not satisfied appearing in version 2.2.7 (not present in 2.2.6)

### ISSUE THREAD

**Issue by stephanemagnenat** [diesel-rs/diesel#4483]
### Versions

- **Rust: 1.81**
- **Diesel: 2.2.7**
- **Database: postgres**
- **Operating System: Ubuntu 22.04.5 LTS**

### Feature Flags

- **diesel: postgres, extras, network-address**

### What are you trying to accomplish?

Compile a code that used to compile correctly with diesel 2.2.6.

### What is the expected output?

A correct compilation

### What is the actual output?

Errors starting with this one:
```
error[E0277]: the trait bound `IpNetwork: diesel::Expression` is not satisfied
  --> log-server/src/model.rs:57:10
   |
57 | #[derive(Insertable, Debug)]
   |          ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `IpNetwork`, which is required by `IpNetwork: AsExpression<diesel::sql_types::Nullable<diesel::sql_types::Inet>>`
```

In a struct:
```
#[derive(Insertable, Debug)]
#[diesel(table_name = session_properties)]
pub struct MyStruct {
   pub ip_address: Option<ipnetwork::IpNetwork>,
   ...
}
```

### Are you seeing any additional errors?

Yes, but they are follow-up errors I think.

### Steps to reproduce

https://github.com/stephanemagnenat/diesel-rs-4483

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate

**Comment by weiznich** [comment]
Thanks for providing that minimal reproducible example.

You can fix that example by just running `cargo update -p ipnetwork@0.21.1 --precise=0.20.0`. There is unfortunately no way for us to communicate to cargo that we want to just use the same version as the upstream application. Feel free to raise this to the cargo team if you have something specific in mind how to improve the situation.

> Could diesel re-export ipnetwork::IpNetwork when the network-address feature is enabled, so that I do not have to depend on a specific version of ipnetwork and avoid breakage upon cargo update?

That would mean that we need to issue a new major diesel release for each major dependency release, so it's unfortunately not feasible. I agree that the situation is not perfect, but as far as I'm aware the current approach is really the best thing we could do with supporting such integrations. The alternatives are either freeze the version of the supported dependency to whatever is supported by the initial stable diesel version or to just not support such integrations at all.

**Comment by stephanemagnenat** [comment]
Thank you for explanation, I'll live with the current situation!
