### ISSUE TITLE
Regression in distinct_on: cannot use .nullable() on column

### ISSUE THREAD

**Issue by Ploppz** [diesel-rs/diesel#3766]
### Versions

- **Rust:** rustc 1.71.1
- **Diesel:** 2.1.1
- **Database:** Postgres
- **Operating System** Linux

## Problem Description

Code using `fn distinct_on` works in Diesel `v2.0.1` but not in `v2.1.1`.

Minimal reproducible example: https://gist.github.com/Ploppz/f8235d83f287bb7926655cd91dfba8fa
`Cargo.toml`: `diesel = { version = "=2.0.1", features = ["postgres", "r2d2"] }`

It compiles in `v2.0.1` but in `v2.1.1` there is the compiler error:
```
error[E0277]: the trait bound `NullableExpression<measurement::columns::id>: Column` is not satisfied
  --> src/main.rs:74:10
   |
74 |         .distinct_on(m::id.nullable())
   |          ^^^^^^^^^^^ the trait `Column` is not implemented for `NullableExpression<measurement::columns::id>`
   |
```

So I tried to remove the `nullable()` so the two lines become:
```rust
        .order_by((m::id, wj::submit_date.nullable().desc()))
        .distinct_on(m::id)
```
But then I get the error:
```
error[E0271]: type mismatch resolving `<Only<table> as AppearsInFromClause<table>>::Count == Never`
  --> src/main.rs:74:10
   |
74 |         .distinct_on(m::id)
   |          ^^^^^^^^^^^ expected `Once`, found `Never`
   |
```
Which makes sense I guess, because the `measurement` table is left-joined so `m::id` is not always present.

## Checklist

- [X] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [X] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [X] This issue can be reproduced without requiring a third party crate
