### ISSUE TITLE
Postgres upsert regression in diesel 2.0.1

### ISSUE THREAD

**Issue by jgallagher** [diesel-rs/diesel#3368]
I believe there's a regression in diesel 2.0.1 coming from 2.0.0 related to https://github.com/diesel-rs/diesel/issues/3330. That issue has a couple notes about the placement of WHERE clauses in relation to DO UPDATE upserts, but the linked postgres docs (https://www.postgresql.org/docs/current/sql-insert.html) show the conflict target can _also_ include a WHERE clause; that previously worked with diesel 2.0.0 but no longer compiles in 2.0.1.

I put an attempt at a minimal reproducer here: https://github.com/jgallagher/diesel-2-0-1-regression. The salient details are that we have a table with a unique index that itself involves another column:

```sql
CREATE TABLE items (
    id SERIAL PRIMARY KEY,
    name VARCHAR NOT NULL,
    time_deleted TIMESTAMPTZ
);

CREATE UNIQUE INDEX ON items (
    name
) WHERE
    time_deleted IS NULL;
```

that restrict item names to unique _if_ their `time_deleted` column IS NULL, but names with a non-NULL `time_deleted` are not required to be unique. We can then upsert with this query in diesel 2.0.0:

```rust
    let query = diesel::insert_into(dsl::items)
        .values(NewItem { name, time_deleted: None })
        .on_conflict(dsl::name)
        .filter_target(dsl::time_deleted.is_null())
        .do_nothing()
        .returning(Item::as_returning());
```

which produces a query with a correct WHERE clause as part of the conflict target:

```sql
INSERT INTO "items" ("name", "time_deleted") VALUES ($1, DEFAULT)
    ON CONFLICT ("name") WHERE ("items"."time_deleted" IS NULL)
    DO NOTHING RETURNING "items"."id", "items"."name", "items"."time_deleted"
```

However, this same query now fails to compile in diesel 2.0.1:

```
error[E0277]: the trait bound `query_builder::upsert::on_conflict_clause::OnConflictValues<query_builder::insert_statement::ValuesClause<(DefaultableColumnInsertValue<ColumnInsertValue<columns::name, diesel::expression::bound::Bound<Text, &str>>>, Defaultab
leColumnInsertValue<ColumnInsertValue<columns::time_deleted, diesel::expression::bound::Bound<diesel::sql_types::Nullable<diesel::sql_types::Timestamptz>, DateTime<Utc>>>>), table>, query_builder::upsert::on_conflict_target_decorations::DecoratedConflictTar
get<query_builder::upsert::on_conflict_target::ConflictTarget<columns::name>, query_builder::where_clause::WhereClause<diesel::expression::grouped::Grouped<diesel::expression::operators::IsNull<columns::time_deleted>>>>, query_builder::upsert::on_conflict_a
ctions::DoNothing>: QueryFragment<Pg, pg::backend::PgOnConflictClaues>` is not satisfied
    --> src/main.rs:35:17
     |
35   |     match query.get_result(conn) {
     |                 ^^^^^^^^^^ the trait `QueryFragment<Pg, pg::backend::PgOnConflictClaues>` is not implemented for `query_builder::upsert::on_conflict_clause::OnConflictValues<query_builder::insert_statement::ValuesClause<(DefaultableColumnInsertValue<
ColumnInsertValue<columns::name, diesel::expression::bound::Bound<Text, &str>>>, DefaultableColumnInsertValue<ColumnInsertValue<columns::time_deleted, diesel::expression::bound::Bound<diesel::sql_types::Nullable<diesel::sql_types::Timestamptz>, DateTime<Utc
>>>>), table>, query_builder::upsert::on_conflict_target_decorations::DecoratedConflictTarget<query_builder::upsert::on_conflict_target::ConflictTarget<columns::name>, query_builder::where_clause::WhereClause<diesel::expression::grouped::Grouped<diesel::exp
ression::operators::IsNull<columns::time_deleted>>>>, query_builder::upsert::on_conflict_actions::DoNothing>`
```

---

When running the reproducer the first time (with diesel 2.0.0), you should get output like:

```
query to upsert one: INSERT INTO "items" ("name", "time_deleted") VALUES ($1, DEFAULT) ON CONFLICT ("name") WHERE ("items"."time_deleted" IS NULL) DO NOTHING RETURNING "items"."id", "items"."name", "items"."time_deleted" -- binds: ["one"]
result of upserting one: Some(Item { id: 26, name: "one", time_deleted: None })
query to upsert two: INSERT INTO "items" ("name", "time_deleted") VALUES ($1, DEFAULT) ON CONFLICT ("name") WHERE ("items"."time_deleted" IS NULL) DO NOTHING RETURNING "items"."id", "items"."name", "items"."time_deleted" -- binds: ["two"]
result of upserting two: Some(Item { id: 27, name: "two", time_deleted: None })
```

and subsequent runs should produce:

```
query to upsert one: INSERT INTO "items" ("name", "time_deleted") VALUES ($1, DEFAULT) ON CONFLICT ("name") WHERE ("items"."time_deleted" IS NULL) DO NOTHING RETURNING "items"."id", "items"."name", "items"."time_deleted" -- binds: ["one"]
result of upserting one: None
query to upsert two: INSERT INTO "items" ("name", "time_deleted") VALUES ($1, DEFAULT) ON CONFLICT ("name") WHERE ("items"."time_deleted" IS NULL) DO NOTHING RETURNING "items"."id", "items"."name", "items"."time_deleted" -- binds: ["two"]
result of upserting two: None
```

The `None` is due to the reproducer mapping a `NotFound` error to `None`.

I'm very much not a diesel expert - is it possible to write this query in 2.0.1 given the new restrictions?

**Comment by weiznich** [comment]
Thanks for reporting this.

Seems like I've missed that section in the postgresql documentation while writing the "fix" for #3330 😞 

I think the best way forward it to:
1. Revert #3349 
2. Mark #3330 as feature request instead as bug as refers to something different than what exists. 
3. Release a 2.0.2 version containing this fix.

I will open a PR for the first point soon.

**Comment by weiznich** [comment]
Closed by #3369

**Comment by weiznich** [comment]
I've published diesel 2.0.2 to address this regression.

**Comment by jgallagher** [comment]
Thank you!
