### PR TITLE
Update MSRV on pipelines

### PR DESCRIPTION
**Pull request by JohnTitor**
I'm not sure when we switch to GHA though.
Also tweaks editorconfig for YAML.

### CODE REVIEW

**Comment by JohnTitor** [comment]
libsqlite3-sys-0.17.3 requires 1.40.0 or later:
```
error[E0658]: non exhaustive is an experimental feature
  --> /home/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/libsqlite3-sys-0.17.3/src/lib.rs:20:1
   |
20 | #[non_exhaustive]
   | ^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/44109
```

**Comment by JohnTitor** [comment]
Allowed `needless_doctest_main` lint since it loses readability.

**Comment by JohnTitor** [comment]
The remaining failure should be fixed by #2339.
