### PR TITLE
Fix a compilation error in diesel_derives with the latest version of syn

### LINKED ISSUE #1921: syn 0.15.22 breaks diesel_derives
### Versions

- **Rust:** 1.30.1
- **Diesel:** 1.33
- **Database:** PostgreSQL
- **Operating System** macOS 10.14.1

### Feature Flags

- **diesel:** default

## Problem Description

The latest version of the `syn` crate exports a new `Result` type alias, which collides with `std::result::Result` and makes `diesel_derives` fail to compile.

### What are you trying to accomplish?

Use `diesel_derives`.

### What is the expected output?

`diesel_derives` compiles successfully.

### What is the actual output?

```
error[E0107]: wrong number of type arguments: expected 1, found 2
  --> diesel_derives/src/util.rs:48:84
   |
48 | pub fn ty_for_foreign_derive(item: &DeriveInput, flags: &MetaItem) -> Result<Type, Diagnostic> {
```

### Are you seeing any additional errors?
No

### Steps to reproduce

Compile diesel_derives from master.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

### PR DESCRIPTION
**Pull request by trha**
This PR replaces all glob imports in `diesel_derives/src/utils.rs` with concrete imports to prevent future occurrences of this error.
Closes #1921.

### CODE REVIEW

**Comment by Eijebong** [comment]
This won't compile with syn < 0.15.22 right ? If so please change the version of sun in the Cargo.toml to 0.15.22

Also is this in some unstable API ? If it.s not maybe the right call would be to ask for that version to be yanked

**Comment by weiznich** [comment]
@Eijebong I do not see why it should not work with syn 0.15.21. As far as I understood the issue that is breaking diesel_derives is that syn 0.15.22 exports some type called `Result<T>` from it's main module. We are doing a wild card import of all items from that module, but assume that `Result` refers to the `Result<T, E>` type from the std lib.Therefore compilation will break with the new version. 
The fix just explicitly imports the items that we actually use (so no "wrong" `Result<T>` type is pulled in scope) Those types should exist on previous syn versions, because we used them before.

**Comment by Eijebong** [comment]
Ha then disregard :p

**Comment by weiznich** [comment]
So this seems fine modulo that clippy compiler error. That seems like we need to update clippy … (Will try to look into this this evening)
