### ISSUE TITLE
diesel::Identifiable "No field with column name id"

### ISSUE THREAD

**Issue by vityafx** [diesel-rs/diesel#2125]
### Versions

- **Rust:** 2018, 1.38-nightly
- **Diesel:** 1.4.0
- **Database:** postgresql-10
- **Operating System** Linux, Ubuntu 18.04.2

### Feature Flags

- **diesel:** postgres, chrono, uuid

## Problem Description
When I tried to migrate to new diesel version - 1.4 from 1.0, my project stopped building successfully. The reason of the problem is `diesel::Identifiable` derive:

```rust
#[derive(
    Debug,
    Clone,
    diesel::Queryable,
    diesel::Identifiable,
    diesel::Insertable,
    diesel::Associations,
    diesel::AsChangeset,
    serde::Serialize,
    serde::Deserialize,
)]
#[diesel::table_name = "phones"]
#[diesel::primary_key(imei)]
#[diesel::belongs_to(User)]
pub struct Phone {
    pub imei: i32,
    pub model: String,
    pub vendor: String,
    pub manufacturer: String,
    pub last_sync: DateTime<Utc>,
    pub user_id: Uuid,
}
```

The schema I have is:

```rust
diesel::table! {
    phones (imei) {
        imei -> Int4,
        model -> Text,
        vendor -> Text,
        manufacturer -> Text,
        last_sync -> Timestamptz,
        user_id -> Uuid,
    }
}
```

The error I get is:

```
error: proc-macro derive panicked
  --> src/models.rs:12:5
   |
12 |     diesel::Identifiable,
   |     ^^^^^^^^^^^^^^^^^^^^
   |
   = help: message: No field with column name id

error: aborting due to previous error
```

### What are you trying to accomplish?
Trying to build my project which was able to build on 1.0 version of diesel with a newer version of it.

### What is the expected output?
Everything is fine and builds successfully.

### What is the actual output?
I see an error which states that there is no field `id` in the struct, however, I have clearly told the framework that it should not be looking for it:

```rust
#[diesel::primary_key(imei)]
```

### Are you seeing any additional errors?
No.

### Steps to reproduce
1. Create a table without the `id` field in it.
2. Create a model for it as it is defined above in the first code snippet.

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

I don't mind if you close the issue since I can't use the stable channel (I am using rocket framework as well), but I need an answer. I also doubt it is related to rust at all. I think the problem is that the derive macro `Identifiable` is still looking for a column named `id`, even though it shouldn't.

**Comment by sgrif** [comment]
`diesel::primary_key` should be `primary_key`.
