### ISSUE TITLE
cannot find type `RawValue` in module `diesel::backend` when upgrading 2.04 -> 2.1.0

### ISSUE THREAD

**Issue by mikeyhew** [diesel-rs/diesel#3711]
It looks like `diesel::backend::RawValue` was deprecated and hidden behind the `with-deprecated` feature in diesel 2.1. I'm not sure if this is intended, but it caused a compile error when I upgraded diesel to 2.1.0. In theory this shouldn't happen if diesel is strictly following semver, since it's only a minor version bump. This was actually a bit difficult to test, because I was actually on diesel 2.0.2 before, and when I updated my diesel version to 2.0.4 in Cargo.toml to see if it's broken on that version, cargo actually automatically installed 2.1.0 because it's semver compatible with 2.0.4.

The quick workaround here is to enable the `with-deprecated` feature, which gives you a deprecation warning instead of a compiler error and tells you to use `diesel::backend::Backend::RawValue` directly instead of this type alias.

I'm posting this here because a) I'm curious if this type of breakage was intentional or not, b) if it wasn't, I want to make sure the maintainers aware of it, and c) to help other people with the same issue.

**Comment by weiznich** [comment]
Thanks for opening this issue.

We are well aware of that behavior and it is supposed to be that way. After all semver is all about whats defined as public stable API and whats not. To cite from the [diesel 2.0 documentation](https://docs.diesel.rs/2.0.x/diesel/index.html#crate-feature-flags)

> `with-deprecated`: This feature enables items marked as #[deprecated]. It is enabled by default. disabling this feature explicitly opts out diesels stability guarantee.

Closed as this is not a bug.

**Comment by mikeyhew** [comment]
Ah I see, I didn't realize that was a default feature that I was opting out of (must have done that a while ago and forgotten about it).
