### ISSUE TITLE
"Expression not implemented for Uuid" in 1.2

### ISSUE THREAD

**Issue by jonathanstrong** [diesel-rs/diesel#1628]
### Versions

- **Rust:** 1.27.0-nightly
- **Diesel:** 1.1.2
- **Database:** Postgres
- **Operating System** Ubuntu 16.04

### Feature Flags

- **diesel:** postgres, extras

## Problem Description
On upgrading to v1.2, I'm getting an error I don't understand. This error is not present when trying to compile with v1.1. I have enabled the "uuid" feature (via "extras" feature):

```
error[E0277]: the trait bound `uuid::Uuid: diesel::Expression` is not satisfied
   --> src/lib.rs:207:14
    |
207 |     #[derive(Insertable, Debug)]
    |              ^^^^^^^^^^ the trait `diesel::Expression` is not implemented for `uuid::Uuid`
    |
    = note: required because of the requirements on the impl of `diesel::Expression` for `&uuid::Uuid`
    = note: required because of the requirements on the impl of `diesel::expression::AsExpression<diesel::sql_types::Uuid>` for `&uuid::Uuid`
```

**Comment by Eijebong** [comment]
Check that you don't have multiple versions of uuid in your lockfile
